#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

# npm test

# .husky/pre-commit
# prettier $(git diff --cached --name-only --diff-filter=acmr | sed 's| |\\ |g') --write --ignore-unknown
# git update-index --again
